### ISSUE TITLE
Blank screen after submit order

### ISSUE THREAD

**Issue by scarmani** [coingate/magento-plugin#1]
Hello team

I've got block screen after I submit order
https://newmind.com/coingate/pay/redirect/

I have firecheckout module installed.
http://templates-master.com/magento-one-page-checkout.html

No. clue in logs. What Could Be the Reason…?

**Comment by rytisbitcoin** [comment]
Hello,

Our plugin is not compatible with some plugins which modify checkout page. Apparently, our plugin is not compatible with the Firecheckout module you are using. Unfortunately, since Firecheckout plugin is not free, we have no possibility to check the reason why it is not compatible with our plugin and / or to fix the incompatibility.
